/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register */
        post: operations["register_auth_register_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_admin_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbooks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Workbooks */
        get: operations["list_workbooks_workbooks_get"];
        put?: never;
        /** Import Workbook */
        post: operations["import_workbook_workbooks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbooks/{workbook_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Workbook */
        get: operations["get_workbook_workbooks__workbook_id__get"];
        put?: never;
        post?: never;
        /** Delete Workbook */
        delete: operations["delete_workbook_workbooks__workbook_id__delete"];
        options?: never;
        head?: never;
        /** Rename Workbook */
        patch: operations["rename_workbook_workbooks__workbook_id__patch"];
        trace?: never;
    };
    "/workbooks/{workbook_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Workbook */
        get: operations["download_workbook_workbooks__workbook_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbooks/{workbook_id}/worksheets/{worksheet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Worksheet */
        get: operations["get_worksheet_workbooks__workbook_id__worksheets__worksheet_id__get"];
        /** Edit Worksheet */
        put: operations["edit_worksheet_workbooks__workbook_id__worksheets__worksheet_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbooks/{workbook_id}/child-sheets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Child Sheets */
        get: operations["list_child_sheets_workbooks__workbook_id__child_sheets_get"];
        put?: never;
        /** Create Child Sheet */
        post: operations["create_child_sheet_workbooks__workbook_id__child_sheets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbooks/{workbook_id}/child-sheets/{relationship_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Child Sheet Status */
        get: operations["get_child_sheet_status_workbooks__workbook_id__child_sheets__relationship_id__status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/workbooks/{workbook_id}/child-sheets/{relationship_id}/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Sync Child Sheet */
        post: operations["sync_child_sheet_workbooks__workbook_id__child_sheets__relationship_id__sync_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/worksheets/{worksheet_id}/convert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Convert Worksheet */
        post: operations["convert_worksheet_worksheets__worksheet_id__convert_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversions/{conversion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Conversion */
        get: operations["get_conversion_conversions__conversion_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversions/{conversion_id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Conversion */
        get: operations["download_conversion_conversions__conversion_id__download_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/db": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Db */
        get: operations["health_db_health_db_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_import_workbook_workbooks_post */
        Body_import_workbook_workbooks_post: {
            /** File */
            file: string;
        };
        /** Body_login_auth_login_post */
        Body_login_auth_login_post: {
            /** Grant Type */
            grant_type?: string | null;
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Scope
             * @default
             */
            scope: string;
            /** Client Id */
            client_id?: string | null;
            /**
             * Client Secret
             * Format: password
             */
            client_secret?: string | null;
        };
        /** CellData */
        CellData: {
            /** Row */
            row: number;
            /** Column */
            column: number;
            /** Value */
            value?: unknown;
            /** Formula */
            formula?: string | null;
            /** Calculated Value */
            calculated_value?: unknown;
            /** Number Format */
            number_format: string;
            /** Bold */
            bold: boolean;
            /** Italic */
            italic: boolean;
            /** Font Color */
            font_color?: string | null;
            /** Fill Color */
            fill_color?: string | null;
            /** Horizontal Alignment */
            horizontal_alignment?: string | null;
            /** Vertical Alignment */
            vertical_alignment?: string | null;
            /** Borders */
            borders: {
                [key: string]: string | null;
            };
        };
        /** CellEdit */
        CellEdit: {
            /** Row */
            row: number;
            /** Column */
            column: number;
            /** Value */
            value?: unknown;
        };
        /** ChildSheetCreateRequest */
        ChildSheetCreateRequest: {
            /**
             * Parent Worksheet Id
             * Format: uuid
             */
            parent_worksheet_id: string;
            /** Child Sheet Name */
            child_sheet_name: string;
            /** Selected Columns */
            selected_columns: string[];
            /**
             * Filter Criteria
             * @default {
             *       "logic": "AND",
             *       "conditions": []
             *     }
             */
            filter_criteria: {
                [key: string]: unknown;
            };
        };
        /** ChildSheetCreateResponse */
        ChildSheetCreateResponse: {
            worksheet: components["schemas"]["WorksheetRead"];
            relationship: components["schemas"]["SheetRelationshipRead"];
        };
        /** ChildSheetStatus */
        ChildSheetStatus: {
            /**
             * Relationship Id
             * Format: uuid
             */
            relationship_id: string;
            /** Is Outdated */
            is_outdated: boolean;
            /** Last Synced At */
            last_synced_at: string | null;
        };
        /** ConversionCreateResponse */
        ConversionCreateResponse: {
            conversion: components["schemas"]["ConversionRead"];
            word_document: components["schemas"]["WordDocumentRead"];
        };
        /** ConversionRead */
        ConversionRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Worksheet Id
             * Format: uuid
             */
            worksheet_id: string;
            /**
             * Requested By Id
             * Format: uuid
             */
            requested_by_id: string;
            /** Status */
            status: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** SheetRelationshipRead */
        SheetRelationshipRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Parent Worksheet Id
             * Format: uuid
             */
            parent_worksheet_id: string;
            /**
             * Child Worksheet Id
             * Format: uuid
             */
            child_worksheet_id: string;
            /** Selected Columns */
            selected_columns: string[];
            /** Filter Criteria */
            filter_criteria: {
                [key: string]: unknown;
            };
            /** Last Synced At */
            last_synced_at: string | null;
        };
        /** Token */
        Token: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
            /** Full Name */
            full_name?: string | null;
        };
        /** UserRead */
        UserRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string | null;
            /** Role */
            role: string;
            /** Is Active */
            is_active: boolean;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WordDocumentRead */
        WordDocumentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** File Size Bytes */
            file_size_bytes: number | null;
            /** Downloaded At */
            downloaded_at: string | null;
        };
        /** WorkbookDetail */
        WorkbookDetail: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** File Size Bytes */
            file_size_bytes: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Worksheets */
            worksheets: components["schemas"]["WorksheetRead"][];
        };
        /** WorkbookRead */
        WorkbookRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Filename */
            filename: string;
            /** File Size Bytes */
            file_size_bytes: number | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** WorkbookUpdate */
        WorkbookUpdate: {
            /** Filename */
            filename: string;
        };
        /** WorksheetData */
        WorksheetData: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Max Row */
            max_row: number;
            /** Max Column */
            max_column: number;
            /** Cells */
            cells: components["schemas"]["CellData"][];
            /** Merged Cells */
            merged_cells: string[];
            /** Column Widths */
            column_widths: {
                [key: string]: number;
            };
            /** Row Heights */
            row_heights: {
                [key: string]: number;
            };
        };
        /** WorksheetEditRequest */
        WorksheetEditRequest: {
            /** Edits */
            edits: components["schemas"]["CellEdit"][];
        };
        /** WorksheetRead */
        WorksheetRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Workbook Id
             * Format: uuid
             */
            workbook_id: string;
            /** Name */
            name: string;
            /** Sheet Type */
            sheet_type: string;
            /** Position */
            position: number | null;
            /**
             * Content Updated At
             * Format: date-time
             */
            content_updated_at: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register_auth_register_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["Body_login_auth_login_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"];
                };
            };
        };
    };
    list_users_admin_users_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRead"][];
                };
            };
        };
    };
    list_workbooks_workbooks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkbookRead"][];
                };
            };
        };
    };
    import_workbook_workbooks_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_import_workbook_workbooks_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkbookRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_workbook_workbooks__workbook_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workbook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkbookDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_workbook_workbooks__workbook_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workbook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_workbook_workbooks__workbook_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workbook_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkbookUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkbookRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_workbook_workbooks__workbook_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workbook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_worksheet_workbooks__workbook_id__worksheets__worksheet_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workbook_id: string;
                worksheet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorksheetData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_worksheet_workbooks__workbook_id__worksheets__worksheet_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workbook_id: string;
                worksheet_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorksheetEditRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorksheetRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_child_sheets_workbooks__workbook_id__child_sheets_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workbook_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetRelationshipRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_child_sheet_workbooks__workbook_id__child_sheets_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workbook_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChildSheetCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildSheetCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_child_sheet_status_workbooks__workbook_id__child_sheets__relationship_id__status_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workbook_id: string;
                relationship_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChildSheetStatus"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    sync_child_sheet_workbooks__workbook_id__child_sheets__relationship_id__sync_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                workbook_id: string;
                relationship_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SheetRelationshipRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    convert_worksheet_worksheets__worksheet_id__convert_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                worksheet_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversionCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_conversion_conversions__conversion_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversionRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_conversion_conversions__conversion_id__download_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                conversion_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    health_db_health_db_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
